name: Build pkgdown Website

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages("pkgdown")'
      - name: Build site
        run: Rscript -e 'pkgdown::build_site()'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
